version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/html
      - ./log/php_errors.log:/var/log/php_errors.log
#    environment:
#      - XDEBUG_CONFIG=remote_host=host.docker.internal
    ports:
      - "8000:80"
      - "9000:9000"
